
[[themes]]
name = "Catppuccin-latte"
[themes.palette]
background = "#0a0a13"
foreground = "#4c526a"
black = "#0a0a13"
blue = "#3c60bf"
cyan = "#3b9ac4"
green = "#52764a"
magenta = "#6a4db2"
red = "#8b3341"
white = "#4c526a"
yellow = "#a47c3e"
bright_black = "#262b3a"
bright_blue = "#4d76de"
bright_cyan = "#4da7d6"
bright_green = "#6b8a55"
bright_magenta = "#7f62d0"
bright_red = "#a44450"
bright_white = "#6b708d"
bright_yellow = "#c4a35c"

[themes.component_style]
selection = { bg = "#394b63", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#394b63", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#5c6370" }


[[themes]]
name = "Catppuccin-frappe"
[themes.palette]
background = "#0a0a13"
foreground = "#a5b2cf"
black = "#0a0a13"
blue = "#698ac6"
cyan = "#6cb3bf"
green = "#739561"
magenta = "#927fc0"
red = "#b87d7f"
white = "#a5b2cf"
yellow = "#c7b27c"
bright_black = "#222b3a"
bright_blue = "#7ea4e5"
bright_cyan = "#8dc2d7"
bright_green = "#89a26f"
bright_magenta = "#a791d8"
bright_red = "#ce8e8d"
bright_white = "#bcc8e2"
bright_yellow = "#d9c991"

[themes.component_style]
selection = { bg = "#4b5970", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#4b5970", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#7d8aa2" }


[[themes]]
name = "Catppuccin-macchiato"
[themes.palette]
background = "#0a0a13"
foreground = "#aab8d7"
black = "#0a0a13"
blue = "#6d8fd9"
cyan = "#7bb7c9"
green = "#84a368"
magenta = "#9b84cd"
red = "#bf8688"
white = "#aab8d7"
yellow = "#d0bc81"
bright_black = "#202b43"
bright_blue = "#84a0f1"
bright_cyan = "#8cc1dd"
bright_green = "#96b07b"
bright_magenta = "#ad9bd8"
bright_red = "#d28c8d"
bright_white = "#c1cae1"
bright_yellow = "#dcd090"

[themes.component_style]
selection = { bg = "#4b5771", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#4b5771", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#7f89ab" }


[[themes]]
name = "Catppuccin-mocha"
[themes.palette]
background = "#0a0a13"
foreground = "#bec8e9"
black = "#0a0a13"
blue = "#7a9de8"
cyan = "#82c0de"
green = "#8cb97f"
magenta = "#aa95de"
red = "#cd8e91"
white = "#bec8e9"
yellow = "#e3d592"
bright_black = "#202a46"
bright_blue = "#8eb6fb"
bright_cyan = "#8bd0ea"
bright_green = "#9acb8a"
bright_magenta = "#ba9fe1"
bright_red = "#e29a9c"
bright_white = "#d1daf3"
bright_yellow = "#f0e4ab"

[themes.component_style]
selection = { bg = "#4a5774", modifiers = ["Bold"] }
block_title = { fg = "Magenta" }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Blue" }
playback_progress_bar = { bg = "#4a5774", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
border = {}
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc = { fg = "#8c97b3" }
